//
// colors.inc - A collection of pre-defined colors.
//

vector Beige               = <1.00, 0.90, 0.80>
vector Black               = <0.00, 0.00, 0.00>
vector Blue                = <0.00, 0.00, 1.00>
vector Brass               = <0.80, 0.60, 0.25>
vector Copper              = <0.90, 0.50, 0.40>
vector Cream               = <1.00, 0.95, 0.90>
vector Cyan                = <0.00, 1.00, 1.00>
vector Dark_Gray           = <0.25, 0.25, 0.25>
vector Gold                = <0.80, 0.70, 0.20>
vector Gray                = <0.50, 0.50, 0.50>
vector Green               = <0.00, 1.00, 0.00>
vector Lemon_Yellow        = <1.00, 1.00, 0.50>
vector Lime_Green          = <0.75, 1.00, 0.50>
vector Lt_Gray             = <0.75, 0.75, 0.75>
vector Magenta             = <1.00, 0.00, 1.00>
vector Off_White           = <1.00, 0.975, 0.95>
vector Orange              = <1.00, 0.50, 0.00>
vector Pink                = <1.00, 0.60, 0.75>
vector Plum                = <0.75, 0.20, 0.45>
vector Raspberry           = <0.90, 0.10, 0.40>
vector Red                 = <1.00, 0.00, 0.00>
vector Royal_Blue          = <0.50, 0.00, 1.00>
vector Salmon              = <1.00, 0.25, 0.40>
vector Sky_Blue            = <0.25, 0.50, 1.00>
vector Tan                 = <1.00, 0.80, 0.60>
vector Violet              = <0.5, 0.00, 0.50>
vector White               = <1.00, 1.00, 1.00>
vector Yellow              = <1.00, 1.00, 0.00>

